spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:pts}?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:aadi}
spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Spring Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:yaswanthadithyareddy11@gmail.com}
spring.mail.password=${MAIL_PASSWORD:ihysxerberglznst}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.org.springframework.web=INFO
google.clientId=${GOOGLE_CLIENT_ID:478861245484-spgps6leq11l8sv7kqfqd56cgatss3pe.apps.googleusercontent.com}


server.port=${PORT:8080}

# JWT Secret
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250655368566D5971}
